### ISSUE TITLE
File missing

### ISSUE THREAD

**Issue by SamAct** [DTUWindEnergy/Python4WindEnergy#1]
Hello,
I am trying to run the code in lesson01 example01 but it seems the file "runs_289_295.yawcal-psiA-stairA" is missing. Can you please look into this and upload a dummy file if possible?

Thanks

**Comment by anuactwind** [comment]
We can not access the file with the given file path so the issue.

**Comment by davidovitch** [comment]
Fixed with commit 8f97a5f86e81ce01d80dafb6f8104165fd3ad397.
